namespace: "magic"

global:
  officialOrganization:
    code: "test001"
    name: "Test Organization"

gateway:
  ingress:
    enabled: true
    className: nginx
    annotations: {}
    pathType: Prefix
    web:
      path: /
      pathType: Prefix
      annotations: {}
    api:
      pathPrefix: /_/magic-service
      pathType: ImplementationSpecific
      useRegex: true
      rewriteTarget: /$1
      annotations: {}
    socket:
      pathPrefix: /_/magic-service/socket.io
      pathType: ImplementationSpecific
      useRegex: true
      rewriteTarget: /socket.io/$1
      annotations:
        nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "300"

magic-service:
  image:
    registry: ""
    repository: dtyq/magic-service
    tag: "master"
    pullPolicy: "IfNotPresent"

magic-web:
  image:
    registry: ""
    repository: dtyq/magic-web
    tag: "master"
    pullPolicy: "IfNotPresent"
  proxy:
    webBaseURL: "http://localhost:38080"
