apiVersion: v2
name: magic-service
description: Magic Service
type: application
version: 0.0.1
appVersion: "0.0.1"
home: https://github.com/dtyq/magic
sources:
  - https://github.com/dtyq/artifacts

maintainers:
  - name: "Lighthouse Engine Ops Team"
    email: "ops@dtyq.com"
