apiVersion: v1
{{- $url := .Values.url | default dict }}
{{- $proxy := .Values.proxy | default dict }}
data:
  PORT: {{ .Values.port | default "8080" | quote }}
  TIMEZONE: {{ .Values.timezone | default "Asia/Shanghai" | quote }}
  MAGIC_AMAP_KEY: {{ .Values.amapKey | default "" | quote }}
  MAGIC_APP_ENV: {{ .Values.appEnv | default "saas-prod" | quote }}
  MAGIC_COPYRIGHT: {{ .Values.copyright | default "" | quote }}
  MAGIC_DEFAULT_LANGUAGE: {{ .Values.defaultLanguage | default "zh_CN" | quote }}
  MAGIC_ICP_CODE: {{ .Values.icpCode | default "" | quote }}
  MAGIC_IS_PRIVATE_DEPLOY: {{ .Values.isPrivateDeploy | default "true" | quote }}
  MAGIC_LOGIN_CONFIG: {{ .Values.loginConfig | toJson | default "{}" | quote }}
  MAGIC_SERVICE_BASE_URL: {{ (index $url "serviceBaseUrl") | default (index $proxy "apiBasePath") | default "/_/magic-service" | quote }}
  MAGIC_SOCKET_BASE_URL: {{ (index $url "socketBaseUrl") | default (index $proxy "socketBasePath") | default "/_/magic-service" | quote }}
  MAGIC_WEB_URL: {{ (index $url "webBaseUrl") | default (index $proxy "webBaseURL") | default "http://localhost:38080" | quote }}
  MAGIC_PUBLIC_CDN_URL: {{ .Values.publicCdnUrl | default "" | quote }}
kind: ConfigMap
metadata:
  name: {{ include "common.names.name" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
---
