{{- $global := .Values.global | default dict }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  name: {{ include "common.names.name" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "common.labels.matchLabels" . | nindent 8 }}
      {{- with (.Values.podAnnotations | default .Values.global.podAnnotations) }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
      - {{- if .Values.extraEnvVars }}
        env:
        {{- include "common.tplvalues.render" (dict "value" .Values.extraEnvVars "context" .) | nindent 8 }}
        {{- end }}
        envFrom:
        - configMapRef:
            name: {{ include "common.names.name" . }}
        image: {{ include "common.images.image" (dict "imageRoot" .Values.image "global" .Values.global "chart" .Chart) }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default $global.imagePullPolicy | default "Always" | quote }}
        name: {{ include "common.names.name" . }}
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        {{- if .Values.customLivenessProbe }}
        livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.customLivenessProbe "context" $) | nindent 10 }}
        {{- else if .Values.livenessProbe.enabled }}
        livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.livenessProbe "enabled") "context" $) | nindent 10 }}
        {{- end }}
        {{- if .Values.customReadinessProbe }}
        readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.customReadinessProbe "context" $) | nindent 10 }}
        {{- else if .Values.readinessProbe.enabled }}
        readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.readinessProbe "enabled") "context" $) | nindent 10 }}
        {{- end }}
        {{- if .Values.customStartupProbe }}
        startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.customStartupProbe "context" $) | nindent 10 }}
        {{- else if .Values.startupProbe.enabled }}
        startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.startupProbe "enabled") "context" $) | nindent 10 }}
        {{- end }}
        {{- if .Values.resources }}
        resources: {{- include "common.tplvalues.render" (dict "value" .Values.resources "context" $) | nindent 10 }}
        {{- else if ne (.Values.resourcesPreset | default "small") "none" }}
        resources: {{- include "common.resources.preset" (dict "type" (.Values.resourcesPreset | default "small")) | nindent 10 }}
        {{- end }}
      {{- include "common.images.pullSecrets" (dict "images" (list .Values.image) "global" $global) | nindent 6 }}
      restartPolicy: Always
