apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  name: {{ include "common.names.name" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
spec:
  ports:
  - name: http
    port: {{ .Values.service.port | default 8080 }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort | default 8080 }}
    {{- if and (eq (.Values.service.type | default "ClusterIP") "NodePort") .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
  type: {{ .Values.service.type | default "ClusterIP" }}
