{{- $secretName := include "common.names.name" . }}
{{- $asr := .Values.asr | default dict }}
{{- $qdrant := .Values.qdrant | default dict }}
{{- $tts := .Values.tts | default dict }}
{{- $sandboxToken := include "common.secrets.passwords.manage" (dict "secret" $secretName "key" "SANDBOX_TOKEN" "length" 32 "providedValues" (list "sandboxToken") "context" $) | trimAll "\"" | b64dec }}
{{- $shareEncryptKey := include "common.secrets.passwords.manage" (dict "secret" $secretName "key" "SHARE_ENCRYPT_KEY" "length" 32 "providedValues" (list "shareEncryptKey") "context" $) | trimAll "\"" | b64dec }}
{{- $shareEncryptIv := include "common.secrets.passwords.manage" (dict "secret" $secretName "key" "SHARE_ENCRYPT_IV" "length" 16 "providedValues" (list "shareEncryptIv") "context" $) | trimAll "\"" | b64dec }}
{{- $flowModelAesKey := include "common.secrets.passwords.manage" (dict "secret" $secretName "key" "MAGIC_FLOW_MODEL_AES_KEY" "length" 32 "providedValues" (list "flowModelAesKey") "context" $) | trimAll "\"" | b64dec }}
{{- $privilegedPassword := include "common.secrets.passwords.manage" (dict "secret" $secretName "key" "MAGIC_PRIVILEGED_PASSWORD" "length" 32 "providedValues" (list "privilegedPassword") "context" $) | trimAll "\"" | b64dec }}
{{- $openPlatformMessageDecryptKey := include "common.secrets.passwords.manage" (dict "secret" $secretName "key" "OPEN_PLATFORM_MESSAGE_DECRYPT_KEY" "length" 32 "providedValues" (list "openPlatform.encryptKey") "context" $) | trimAll "\"" | b64dec }}
{{- $serviceProviderConfigAesKey := include "common.secrets.passwords.manage" (dict "secret" $secretName "key" "SERVICE_PROVIDER_CONFIG_AES_KEY" "length" 32 "providedValues" (list "serviceProviderConfigAesKey") "context" $) | trimAll "\"" | b64dec }}
{{- $watermarkSignAesKey := include "common.secrets.passwords.manage" (dict "secret" $secretName "key" "WATERMARK_SIGN_AES_KEY" "length" 32 "providedValues" (list "watermarkSignAesKey") "context" $) | trimAll "\"" | b64dec }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ include "common.names.namespace" . | quote }}
type: Opaque
data:
  APP_ID: {{ .Values.appId | default "" | b64enc }}
  APP_SECRET: {{ .Values.appSecret | default "" | b64enc }}
  APP_CODE: {{ .Values.appCode | default "" | b64enc }}
  {{- with $asr.vke }}
  ASR_VKE_APP_ID: {{ .appId | default "" | b64enc }}
  ASR_VKE_CLUSTER: {{ .cluster | default "" | b64enc }}
  ASR_VKE_TOKEN: {{ .token | default "" | b64enc }}
  {{- end }}
  {{- with .Values.bingSearch }}
  BING_SEARCH_API_KEY: {{ .apiKey | default "" | b64enc }}
  BING_SEARCH_ENDPOINT: {{ .endpoint | default "" | b64enc }}
  {{- end }}
  MAGIC_FLOW_MODEL_AES_KEY: {{ $flowModelAesKey | b64enc | quote }}
  MAGIC_PRIVILEGED_PASSWORD: {{ $privilegedPassword | b64enc | quote }}
  OPEN_PLATFORM_MESSAGE_DECRYPT_KEY: {{ $openPlatformMessageDecryptKey | b64enc | quote }}
  SANDBOX_TOKEN: {{ $sandboxToken | b64enc | quote }}
  SERVICE_PROVIDER_CONFIG_AES_KEY: {{ $serviceProviderConfigAesKey | b64enc | quote }}
  SHARE_ENCRYPT_KEY: {{ $shareEncryptKey | b64enc | quote }}
  SHARE_ENCRYPT_IV: {{ $shareEncryptIv | b64enc | quote }}
  {{- with .Values.skylark }}
  SKYLARK_PRO_API_KEY: {{ .apiKey | default "" | b64enc }}
  {{- end }}
  {{- with $tts.vke }}
  TTS_VKE_APP_ID: {{ .appId | default "" | b64enc }}
  TTS_VKE_TOKEN: {{ .token | default "" | b64enc }}
  {{- end }}
  WATERMARK_SIGN_AES_KEY: {{ $watermarkSignAesKey | b64enc | quote }}
  ODIN_QDRANT_API_KEY: {{ $qdrant.apiKey | default "" | b64enc }}
---
