{{- $s3 := .Values.s3 | default dict }}
apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  akId: {{ $s3.accessKey | default "" | b64enc }}
  akSecret: {{ $s3.secretKey | default "" | b64enc }}
