{{- $mysql := .Values.mysql | default dict }}
{{- $redis := .Values.redis | default dict }}
{{- $amqp := .Values.amqp | default dict }}
apiVersion: v1
data:
  DB_PASSWORD: {{ $mysql.password | default "" | b64enc }}
  DB_USERNAME: {{ $mysql.username | default "" | b64enc }}
kind: Secret
metadata:
  name: database
  namespace: {{ include "common.names.namespace" . | quote }}
type: Opaque
---
apiVersion: v1
data:
  REDIS_AUTH: {{ $redis.auth | default "" | b64enc }}
kind: Secret
metadata:
  name: redis
  namespace: {{ include "common.names.namespace" . | quote }}
type: Opaque
---
apiVersion: v1
data:
  AMQP_PASSWORD: {{ $amqp.password | default "" | b64enc }}
  AMQP_USER: {{ $amqp.user | default "" | b64enc }}
kind: Secret
metadata:
  name: amqp
  namespace: {{ include "common.names.namespace" . | quote }}
type: Opaque
