{{- $mysql := .Values.mysql | default dict }}
{{- $redis := .Values.redis | default dict }}
{{- $amqp := .Values.amqp | default dict }}
{{- $fd := .Values.fileDriver | default dict }}
apiVersion: v1
data:
  DB_PASSWORD: {{ $mysql.password | default "" | b64enc }}
  DB_USERNAME: {{ $mysql.username | default "" | b64enc }}
kind: Secret
metadata:
  name: database
  namespace: {{ include "common.names.namespace" . | quote }}
type: Opaque
---
apiVersion: v1
data:
  REDIS_AUTH: {{ $redis.auth | default "" | b64enc }}
kind: Secret
metadata:
  name: redis
  namespace: {{ include "common.names.namespace" . | quote }}
type: Opaque
---
apiVersion: v1
data:
  AMQP_PASSWORD: {{ $amqp.password | default "" | b64enc }}
  AMQP_USER: {{ $amqp.user | default "" | b64enc }}
kind: Secret
metadata:
  name: amqp
  namespace: {{ include "common.names.namespace" . | quote }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: file-driver
  namespace: {{ include "common.names.namespace" . | quote }}
type: Opaque
data:
  {{- with $fd.tos | default dict }}
  {{- with .private | default dict }}
  FILE_PRIVATE_TOS_AK: {{ .accessKey | default "" | b64enc | quote }}
  FILE_PRIVATE_TOS_SK: {{ .secretKey | default "" | b64enc | quote }}
  {{- end }}
  {{- with .public | default dict }}
  FILE_PUBLIC_TOS_AK: {{ .accessKey | default "" | b64enc | quote }}
  FILE_PUBLIC_TOS_SK: {{ .secretKey | default "" | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- with $fd.oss | default dict }}
  {{- with .private | default dict }}
  FILE_PRIVATE_ALIYUN_ACCESS_ID: {{ .accessKey | default "" | b64enc | quote }}
  FILE_PRIVATE_ALIYUN_ACCESS_SECRET: {{ .secretKey | default "" | b64enc | quote }}
  {{- end }}
  {{- with .public | default dict }}
  FILE_PUBLIC_ALIYUN_ACCESS_ID: {{ .accessKey | default "" | b64enc | quote }}
  FILE_PUBLIC_ALIYUN_ACCESS_SECRET: {{ .secretKey | default "" | b64enc | quote }}
  {{- end }}
  {{- end }}
---
